# Generated by Django 5.2.12 on 2026-05-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_url', models.URLField()),
                ('branch', models.CharField(default='main', max_length=100)),
                ('container_port', models.IntegerField(default=8000)),
                ('deployed_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_DEPLOYED', 'Not Deployed'), ('DEPLOYING', 'Deploying'), ('RUNNING', 'Running'), ('FAILED', 'Failed')], default='NOT_DEPLOYED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
