# Generated by Django 6.0.5 on 2026-06-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_container_name_project_host_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='container_port',
        ),
    ]
