# Generated by Django 6.0.5 on 2026-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_project_container_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='route_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NOT_DEPLOYED', 'Not Deployed'), ('QUEUED', 'Queued'), ('DEPLOYING', 'Deploying'), ('RUNNING', 'Running'), ('FAILED', 'Failed')], default='NOT_DEPLOYED', max_length=20),
        ),
    ]
