# Generated by Django 6.0.5 on 2026-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_project_route_name_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_logs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
