# Generated by Django 6.0.5 on 2026-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_deployment_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment_progress',
            field=models.IntegerField(default=0),
        ),
    ]
