# Generated by Django 6.0.5 on 2026-06-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_project_deployment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_deployed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
