# Generated by Django 6.0.5 on 2026-06-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
